"""Constants"""

from dataclasses import dataclass

TEST_PROJECT_PATH: str = "Thermos Output for Testing/thermos.qgz"


@dataclass
class ThermosFields:
    """Field names for Thermos results"""

    id: str = "id"
    type: str = "candidate/user-fields Category"
    in_solution: str = "solution/included"
    demand: str = "demand/kwp"
    dim: str = "solution/diameter-mm"
    pipe_start: str = "path/start"
    pipe_end: str = "path/end"


THERMOS_FIELD_NAMES: list[str] = [
    "candidate/connections 0",
    "candidate/connections 1",
    "candidate/connections 2",
    "candidate/connections 3",
    "candidate/connections 4",
    "candidate/connections 5",
    "candidate/ground-area",
    "candidate/id",
    "candidate/inclusion",
    "candidate/modified",
    "candidate/roof-area",
    "candidate/selected",
    "candidate/type",
    "candidate/user-fields Category",
    "candidate/user-fields Height",
    "candidate/user-fields Name",
    "candidate/wall-area",
    "cooling/kwh",
    "cooling/kwp",
    "demand/connection-count",
    "demand/group",
    "demand/kwh",
    "demand/kwp",
    "demand/source",
    "id",
    "path/end",
    "path/length",
    "path/start",
    "solution/capacity-kw",
    "solution/connected",
    "solution/connection-capex annual",
    "solution/connection-capex present",
    "solution/connection-capex principal",
    "solution/connection-capex total",
    "solution/connection-capex type",
    "solution/counterfactual",
    "solution/diameter-mm",
    "solution/diversity",
    "solution/heat-cost annual",
    "solution/heat-cost present",
    "solution/heat-cost total",
    "solution/heat-cost type",
    "solution/heat-revenue annual",
    "solution/heat-revenue present",
    "solution/heat-revenue total",
    "solution/heat-revenue type",
    "solution/included",
    "solution/kwh",
    "solution/kwp",
    "solution/length-factor",
    "solution/losses-kwh",
    "solution/max-capacity-kw",
    "solution/output-kwh",
    "solution/pipe-capex annual",
    "solution/pipe-capex present",
    "solution/pipe-capex principal",
    "solution/pipe-capex total",
    "solution/pipe-capex type",
    "solution/pumping-cost annual",
    "solution/pumping-cost present",
    "solution/pumping-cost total",
    "solution/pumping-cost type",
    "solution/pumping-emissions co2 annual",
    "solution/pumping-emissions co2 kg",
    "solution/pumping-emissions co2 present",
    "solution/pumping-emissions co2 type",
    "solution/pumping-emissions co2 total",
    "solution/pumping-emissions nox annual",
    "solution/pumping-emissions nox kg",
    "solution/pumping-emissions nox present",
    "solution/pumping-emissions nox total",
    "solution/pumping-emissions nox type",
    "solution/pumping-emissions pm25 annual",
    "solution/pumping-emissions pm25 kg",
    "solution/pumping-emissions pm25 present",
    "solution/pumping-emissions pm25 total",
    "solution/pumping-emissions pm25 type",
    "solution/pumping-kwh",
    "solution/supply-capex annual",
    "solution/supply-capex present",
    "solution/supply-capex principal",
    "solution/supply-capex total",
    "solution/supply-capex type",
    "solution/supply-emissions co2 annual",
    "solution/supply-emissions co2 kg",
    "solution/supply-emissions co2 present",
    "solution/supply-emissions co2 total",
    "solution/supply-emissions co2 type",
    "solution/supply-emissions nox annual",
    "solution/supply-emissions nox kg",
    "solution/supply-emissions nox present",
    "solution/supply-emissions nox total",
    "solution/supply-emissions nox type",
    "solution/supply-emissions pm25 annual",
    "solution/supply-emissions pm25 kg",
    "solution/supply-emissions pm25 present",
    "solution/supply-emissions pm25 total",
    "solution/supply-emissions pm25 type",
    "solution/supply-opex annual",
    "solution/supply-opex present",
    "solution/supply-opex total",
    "solution/supply-opex type",
    "solution/unreachable",
    "supply/capacity-kwp",
    "supply/profile-id",
    "tariff/cc-id",
    "tariff/id",
]
